recipes:
  - name : lightning-utilities
    path : lightning-utilities

  - name : torchmetrics
    path : metrics

  - name : pytorch-lightning
    path : lightning

  - name : lightning-cloud
    path : lightning-cloud

  - name : lightning-app
    path : lightning-app

  - name : lightning-fabric
    path : lightning-fabric
